src/Entity/PersonalData.php
<?php

namespace App\Entity;

use App\Repository\PersonalDataRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PersonalDataRepository::class)
 */
class PersonalData
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profession;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\OneToMany(targetEntity=SocialLinks::class, mappedBy="personalData")
     */
    private $socialLinks;

    /**
     * @ORM\OneToMany(targetEntity=JobExperience::class, mappedBy="personalData")
     */
    private $jobExperiences;

    /**
     * @ORM\OneToMany(targetEntity=Education::class, mappedBy="personalData")
     */
    private $education;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sent_invitation;

    /**
     * @ORM\Column(type="text")
     */
    private $about;

    public function __toString()
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function __construct()
    {
        $this->socialLinks = new ArrayCollection();
        $this->jobExperiences = new ArrayCollection();
        $this->education = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    /**
     * @return Collection<int, SocialLinks>
     */
    public function getSocialLinks(): Collection
    {
        return $this->socialLinks;
    }

    /**
     * @param SocialLinks $socialLink
     * @return $this
     */
    public function addSocialLink(SocialLinks $socialLink): self
    {
        if (!$this->socialLinks->contains($socialLink)) {
            $this->socialLinks[] = $socialLink;
            $socialLink->setPersonalData($this);
        }

        return $this;
    }

    public function removeSocialLink(SocialLinks $socialLink): self
    {
        if ($this->socialLinks->removeElement($socialLink)) {
            // set the owning side to null (unless already changed)
            if ($socialLink->getPersonalData() === $this) {
                $socialLink->setPersonalData(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, JobExperience>
     */
    public function getJobExperiences(): Collection
    {
        return $this->jobExperiences;
    }

    public function addJobExperience(JobExperience $jobExperience): self
    {
        if (!$this->jobExperiences->contains($jobExperience)) {
            $this->jobExperiences[] = $jobExperience;
            $jobExperience->setPersonalData($this);
        }

        return $this;
    }

    public function removeJobExperience(JobExperience $jobExperience): self
    {
        if ($this->jobExperiences->removeElement($jobExperience)) {
            // set the owning side to null (unless already changed)
            if ($jobExperience->getPersonalData() === $this) {
                $jobExperience->setPersonalData(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Education>
     */
    public function getEducation(): Collection
    {
        return $this->education;
    }

    public function addEducation(Education $education): self
    {
        if (!$this->education->contains($education)) {
            $this->education[] = $education;
            $education->setPersonalData($this);
        }

        return $this;
    }

    public function removeEducation(Education $education): self
    {
        if ($this->education->removeElement($education)) {
            // set the owning side to null (unless already changed)
            if ($education->getPersonalData() === $this) {
                $education->setPersonalData(null);
            }
        }

        return $this;
    }

    public function getSentInvitation(): ?bool
    {
        return $this->sent_invitation;
    }

    public function setSentInvitation(bool $sent_invitation): self
    {
        $this->sent_invitation = $sent_invitation;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(string $about): self
    {
        $this->about = $about;

        return $this;
    }
}

src/Form/PersonalDataType.php
<?php

namespace App\Form;

use App\Entity\PersonalData;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonalDataType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('email')
            ->add('phone')
            ->add('adress')
            ->add('profession')
            ->add('about')
            ->add('active')
            ->add('visible')
            ->add('birthday')
            ->add('sent_invitation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PersonalData::class,
        ]);
    }
}

src/Controller/PersonalDataController.php
<?php

namespace App\Controller;

use App\Entity\PersonalData;
use App\Form\PersonalDataType;
use App\Repository\PersonalDataRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/personal/data")
 */
class PersonalDataController extends AbstractController
{
    /**
     * @Route("/", name="app_personal_data_index", methods={"GET"})
     */
    public function index(PersonalDataRepository $personalDataRepository): Response
    {
        return $this->render('personal_data/index.html.twig', [
            'personal_datas' => $personalDataRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_personal_data_new", methods={"GET", "POST"})
     */
    public function new(Request $request, PersonalDataRepository $personalDataRepository): Response
    {
        $personalDatum = new PersonalData();
        $form = $this->createForm(PersonalDataType::class, $personalDatum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $personalDataRepository->add($personalDatum);
            return $this->redirectToRoute('app_personal_data_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('personal_data/new.html.twig', [
            'personal_datum' => $personalDatum,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_personal_data_show", methods={"GET"})
     */
    public function show(PersonalData $personalDatum): Response
    {
        return $this->render('personal_data/show.html.twig', [
            'personal_datum' => $personalDatum,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_personal_data_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, PersonalData $personalDatum, PersonalDataRepository $personalDataRepository): Response
    {
        $form = $this->createForm(PersonalDataType::class, $personalDatum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $personalDataRepository->add($personalDatum);
            return $this->redirectToRoute('app_personal_data_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('personal_data/edit.html.twig', [
            'personal_datum' => $personalDatum,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_personal_data_delete", methods={"POST"})
     */
    public function delete(Request $request, PersonalData $personalDatum, PersonalDataRepository $personalDataRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$personalDatum->getId(), $request->request->get('_token'))) {
            $personalDataRepository->remove($personalDatum);
        }

        return $this->redirectToRoute('app_personal_data_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/personal_data/_delete_form.html.twig
<form method="post" action="{{ path('app_personal_data_delete', {'id': personal_datum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personal_datum.id) }}">
    <button class="btn">Delete</button>
</form>

templates/personal_data/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/personal_data/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PersonalData{% endblock %}

{% block body %}
    <h1>Edit PersonalData</h1>

    {{ include('personal_data/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_personal_data_index') }}">back to list</a>

    {{ include('personal_data/_delete_form.html.twig') }}
{% endblock %}

templates/personal_data/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PersonalData index{% endblock %}

{% block body %}

    <a href="{{ path('index') }}">Index</a>
    <h1>PersonalData index</h1>

    <table class="table">
        <thead>`
            <tr>
                <th>Id</th>
                <th>FirstName</th>
                <th>LastName</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Adress</th>
                <th>About</th>
                <th>Profession</th>
                <th>Active</th>
                <th>Visible</th>
                <th>Birthday</th>
                <th>Sent_invitation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for personal_datum in personal_datas %}
            <tr>
                <td>{{ personal_datum.id }}</td>
                <td>{{ personal_datum.firstName }}</td>
                <td>{{ personal_datum.lastName }}</td>
                <td>{{ personal_datum.email }}</td>
                <td>{{ personal_datum.phone }}</td>
                <td>{{ personal_datum.adress }}</td>
                <td>{{ personal_datum.about }}</td>
                <td>{{ personal_datum.profession }}</td>
                <td>{{ personal_datum.active ? 'Yes' : 'No' }}</td>
                <td>{{ personal_datum.visible ? 'Yes' : 'No' }}</td>
                <td>{{ personal_datum.birthday ? personal_datum.birthday|date('Y-m-d') : '' }}</td>
                <td>{{ personal_datum.sentInvitation ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_personal_data_show', {'id': personal_datum.id}) }}">show</a>
                    <a href="{{ path('app_personal_data_edit', {'id': personal_datum.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_personal_data_new') }}">Create new</a>
{% endblock %}

templates/personal_data/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New PersonalData{% endblock %}

{% block body %}
    <h1>Create new PersonalData</h1>

    {{ include('personal_data/_form.html.twig') }}

    <a href="{{ path('app_personal_data_index') }}">back to list</a>
{% endblock %}

templates/personal_data/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PersonalData{% endblock %}

{% block body %}
    <h1>PersonalData</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personal_datum.id }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ personal_datum.firstName }}</td>
            </tr>
            <tr>
                <th>LastName</th>
                <td>{{ personal_datum.lastName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ personal_datum.email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ personal_datum.phone }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ personal_datum.adress }}</td>
            </tr>
            <tr>
                <th>About</th>
                <td>{{ personal_datum.about }}</td>
            </tr>
            <tr>
                <th>Profession</th>
                <td>{{ personal_datum.profession }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ personal_datum.active ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Visible</th>
                <td>{{ personal_datum.visible ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Birthday</th>
                <td>{{ personal_datum.birthday ? personal_datum.birthday|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Sent_invitation</th>
                <td>{{ personal_datum.sentInvitation ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_personal_data_index') }}">back to list</a>

    <a href="{{ path('app_personal_data_edit', {'id': personal_datum.id}) }}">edit</a>

    {{ include('personal_data/_delete_form.html.twig') }}
{% endblock %}