src/Entity/Education.php
<?php

namespace App\Entity;

use App\Repository\EducationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EducationRepository::class)
 */
class Education
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $degreeName;

    /**
     * @ORM\Column(type="date")
     */
    private $graduationDate;

    /**
     * @ORM\ManyToOne(targetEntity=PersonalData::class, inversedBy="education", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $personalData;

    /**
     * @ORM\ManyToOne(targetEntity=DegreeType::class, inversedBy="education", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $speciality;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Faculty;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDegreeName(): ?string
    {
        return $this->degreeName;
    }

    public function setDegreeName(string $degreeName): self
    {
        $this->degreeName = $degreeName;

        return $this;
    }

    public function getGraduationDate(): ?\DateTimeInterface
    {
        return $this->graduationDate;
    }

    public function setGraduationDate(\DateTimeInterface $graduationDate): self
    {
        $this->graduationDate = $graduationDate;

        return $this;
    }

    public function getPersonalData(): ?PersonalData
    {
        return $this->personalData;
    }

    public function setPersonalData(?PersonalData $personalData): self
    {
        $this->personalData = $personalData;

        return $this;
    }

    public function getType(): ?DegreeType
    {
        return $this->type;
    }

    public function setType(?DegreeType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getSpeciality(): ?string
    {
        return $this->speciality;
    }

    public function setSpeciality(string $speciality): self
    {
        $this->speciality = $speciality;

        return $this;
    }

    public function getFaculty(): ?string
    {
        return $this->Faculty;
    }

    public function setFaculty(string $Faculty): self
    {
        $this->Faculty = $Faculty;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
<body>
{% block body %}
    <div class="main_nav d-flex flex-row align-items-end justify-content-start">
        <ul class="d-flex flex-column align-items-start justify-content-start">
            <li><a href="{{ path('app_personal_data_index') }}">Personal Data (User)</a></li>
            <li><a href="{{ path('app_job_experience_index') }}">Job Experience</a></li>
            <li><a href="{{ path('app_degree_type_index') }}">Degree</a></li>
            <li><a href="{{ path('app_social_link_type_index') }}">Social media types</a></li>
            <li><a href="{{ path('app_social_links_index') }}">Social media links</a></li>
            <li><a href="{{ path('app_education_index') }}">Education</a></li>
        </ul>
    </div>
{% endblock %}
</body>
</html>

templates/head.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Resume - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{{ asset('build/styles/app.css') }}" rel="stylesheet" />
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/manage.html.twig
{{ include('head.html.twig') }}
{% block body %}
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">{{ personal_data.first_name ~ ' ' ~ personal_data.last_name }}</span>
            <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2"
                                                 src="{{ asset('build/images/victoria.png') }}" alt="..."/></span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">Home</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Experienţă</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education">Educaţie</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills">Skills</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#manage">Manage</a></li>
            </ul>
        </div>
    </nav>
    <!-- Page Content-->
    <div class="container-fluid p-0">
        <!-- About-->
        <section class="resume-section" id="about">
            <div class="resume-section-content">
                <h1 class="mb-0">
                    {{ personal_data.first_name }}
                    <span class="text-primary">{{ personal_data.last_name }}</span>
                </h1>
                <div class="subheading mb-5">
                    {{ personal_data.address }} · {{ personal_data.phone }} ·
                    <a href="mailto:name@email.com">{{ personal_data.email }}</a>
                </div>
                <p class="lead mb-5">{{ personal_data.about }}</p>
                <div class="social-icons">
                    {% for social_link in social_links %}
                        {% set value = social_link.type %}
                        {% if value == 'linkedin' %}
                            <a class="social-icon" href="{{ social_link.link }}" target="_blank"><i
                                        class="fab fa-linkedin-in"></i></a>
                        {% endif %}
                        {% if value == 'github' %}
                            <a class="social-icon" href="{{ social_link.link }}" target="_blank"><i
                                        class="fab fa-github"></i></a>
                        {% endif %}
                        {% if value == 'twitter' %}
                            <a class="social-icon" href="{{ social_link.link }}" target="_blank"><i
                                        class="fab fa-twitter"></i></a>
                        {% endif %}
                        {% if value == 'facebook' %}
                            <a class="social-icon" href="{{ social_link.link }}" target="_blank"><i
                                        class="fab fa-facebook-f"></i></a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </section>
        <hr class="m-0"/>
        <!-- Experience-->
        <section class="resume-section" id="experience">
            <div class="resume-section-content">
                <h2 class="mb-5">Experienţă</h2>
                {% for experience in job_experience %}
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">{{ experience.position }}</h3>
                            <div class="subheading mb-3">{{ experience.company }}</div>
                            <p>{{ experience.description }}</p>
                        </div>
                        <div class="flex-shrink-0"><span
                                    class="text-primary">{{ experience.start_date ~ ' - ' ~ experience.end_date }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
        <hr class="m-0"/>
        <!-- Education-->
        <section class="resume-section" id="education">
            <div class="resume-section-content">
                <h2 class="mb-5">Educaţie</h2>
                {% for education in education %}
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">{{ education.degree_name }}</h3>
                            <div class="subheading mb-3">{{ education.speciality }}</div>
                            <p>{{ education.faculty }}</p>
                            <div>Master</div>
                        </div>
                        <div class="flex-shrink-0"><span
                                    class="text-primary">{{ education.graduation_date }}</span></div>
                    </div>
                {% endfor %}
            </div>
        </section>
        <hr class="m-0"/>
        <!-- Skills-->
        <section class="resume-section" id="skills">
            <div class="resume-section-content">
                <h2 class="mb-5">Skills</h2>
                <div class="subheading mb-3">Programming Languages & Tools</div>
                <ul class="list-inline dev-icons">
                    <li class="list-inline-item"><i class="fab fa-html5"></i></li>
                    <li class="list-inline-item"><i class="fab fa-css3-alt"></i></li>
                    <li class="list-inline-item"><i class="fab fa-js-square"></i></li>
                    <li class="list-inline-item"><i class="fab fa-angular"></i></li>
                    <li class="list-inline-item"><i class="fab fa-react"></i></li>
                    <li class="list-inline-item"><i class="fab fa-node-js"></i></li>
                    <li class="list-inline-item"><i class="fab fa-sass"></i></li>
                    <li class="list-inline-item"><i class="fab fa-less"></i></li>
                    <li class="list-inline-item"><i class="fab fa-wordpress"></i></li>
                    <li class="list-inline-item"><i class="fab fa-gulp"></i></li>
                    <li class="list-inline-item"><i class="fab fa-grunt"></i></li>
                    <li class="list-inline-item"><i class="fab fa-npm"></i></li>
                </ul>

            </div>
        </section>
        <hr class="m-0"/>
        <section class="resume-section" id="manage">
            {{ include('base.html.twig') }}
        </section>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{{ asset('build/js/scripts.js') }}"></script>
{% endblock %}